version: '3.8'

services:

  makassar_management_react:
    image: thenatz1999/makassar-management-react-prod:0.0.8
    container_name: makassar-mgmt-react
    pull_policy: always
    restart: always
    ports:
      - "3000:3000"
    environment: {}

  makassar_management_api:
    image: thenatz1999/makassar-management-api-prod:0.0.8
    container_name: makassar-mgmt-api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /makassar-management/data/api-prod-uploads:/app/uploads
    environment:
      MONGO_USER: ""
      MONGO_PASSWORD: ""
      MONGO_DBNAME: ""
      MONGO_HOST: "mongoDB"
    depends_on:
      - mongoDB




  mongoDB:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
      MONGO_INITDB_DATABASE: ""
    ports:
      - "27017:27017"
    #        - "27018:27018"  # SSL Port
    volumes:
      - /makassar-management/data/mongo-prod-data:/data/db
#        - /makassar-management/mongo-config/mongod.conf:/etc/mongod.conf.orig
#        - /makassar-management/mongo-config/mongo-certs:/etc/ssl/mongo  # Mount SSL certificates
#      command: >
#        mongod
#        --tlsMode preferTLS
#        --tlsCertificateKeyFile /etc/ssl/mongo/mongo.pem
#        --tlsCAFile /etc/ssl/mongo/ca.pem