ktor:
    application:
        modules:
            - com.makassar.ApplicationKt.module
    deployment:
        port: 8080
    database:
        mongo:
            user: "mongo-makassar"
            password: "mongo-makassar-password"
            host: "localhost"
            port: "27017"
            #maxPoolSize: 10
            dbname: makassar-management-db-dev
    appConfig:

    environment:
        allowedUploadFileTypes: "png,jpeg,jpg"




jwt:
    secret:  "secret"
    issuer: "http://0.0.0.0:8080/"
    audience: "http://0.0.0.0:8080"
    realm: "Access to api"
    accessToken:
        lifetime: 600000000
        #lifetime: 30000
    refreshToken:
        lifetime: 3600000
